# Generated by Django 2.1.4 on 2019-03-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190313_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='title',
        ),
    ]
