# Generated by Django 2.1.4 on 2019-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_group_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
