# Generated by Django 2.1.4 on 2019-03-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='like',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
